// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos.proto at 5:1
package com.bubbletastic.android.ping.model.proto;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum HostStatus implements WireEnum {
  unknown(0),

  reachable(1),

  unreachable(2),

  updating(3);

  public static final ProtoAdapter<HostStatus> ADAPTER = ProtoAdapter.newEnumAdapter(HostStatus.class);

  private final int value;

  HostStatus(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static HostStatus fromValue(int value) {
    switch (value) {
      case 0: return unknown;
      case 1: return reachable;
      case 2: return unreachable;
      case 3: return updating;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
