// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../app/proto/protos.proto
package com.bubbletastic.android.ping.model.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class HostsContainer extends Message {
  private static final long serialVersionUID = 0L;

  public static final List<ProtoHost> DEFAULT_HOSTS = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED, messageType = ProtoHost.class)
  public final List<ProtoHost> hosts;

  public HostsContainer(List<ProtoHost> hosts) {
    this.hosts = immutableCopyOf(hosts);
  }

  private HostsContainer(Builder builder) {
    this(builder.hosts);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof HostsContainer)) return false;
    return equals(hosts, ((HostsContainer) other).hosts);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = hosts != null ? hosts.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<HostsContainer> {

    public List<ProtoHost> hosts;

    public Builder() {
    }

    public Builder(HostsContainer message) {
      super(message);
      if (message == null) return;
      this.hosts = copyOf(message.hosts);
    }

    public Builder hosts(List<ProtoHost> hosts) {
      this.hosts = checkForNulls(hosts);
      return this;
    }

    @Override
    public HostsContainer build() {
      return new HostsContainer(this);
    }
  }
}
