// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../app/proto/protos.proto
package com.bubbletastic.android.ping.model.proto;

import com.squareup.wire.ProtoEnum;

public enum HostStatus
    implements ProtoEnum {
  unknown(0),
  reachable(1),
  unreachable(2),
  updating(3);

  private final int value;

  private HostStatus(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
