// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../app/proto/protos.proto
package com.bubbletastic.android.ping.model.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;

public final class PingResult extends Message {
  private static final long serialVersionUID = 0L;

  public static final HostStatus DEFAULT_STATUS = HostStatus.unreachable;
  public static final Long DEFAULT_PINGED_AT = 0L;
  public static final Integer DEFAULT_ROUND_TRIP_AVG = 0;

  @ProtoField(tag = 1, type = ENUM)
  public final HostStatus status;

  @ProtoField(tag = 2, type = INT64)
  public final Long pinged_at;

  @ProtoField(tag = 3, type = INT32)
  public final Integer round_trip_avg;

  public PingResult(HostStatus status, Long pinged_at, Integer round_trip_avg) {
    this.status = status;
    this.pinged_at = pinged_at;
    this.round_trip_avg = round_trip_avg;
  }

  private PingResult(Builder builder) {
    this(builder.status, builder.pinged_at, builder.round_trip_avg);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PingResult)) return false;
    PingResult o = (PingResult) other;
    return equals(status, o.status)
        && equals(pinged_at, o.pinged_at)
        && equals(round_trip_avg, o.round_trip_avg);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = status != null ? status.hashCode() : 0;
      result = result * 37 + (pinged_at != null ? pinged_at.hashCode() : 0);
      result = result * 37 + (round_trip_avg != null ? round_trip_avg.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PingResult> {

    public HostStatus status;
    public Long pinged_at;
    public Integer round_trip_avg;

    public Builder() {
    }

    public Builder(PingResult message) {
      super(message);
      if (message == null) return;
      this.status = message.status;
      this.pinged_at = message.pinged_at;
      this.round_trip_avg = message.round_trip_avg;
    }

    public Builder status(HostStatus status) {
      this.status = status;
      return this;
    }

    public Builder pinged_at(Long pinged_at) {
      this.pinged_at = pinged_at;
      return this;
    }

    public Builder round_trip_avg(Integer round_trip_avg) {
      this.round_trip_avg = round_trip_avg;
      return this;
    }

    @Override
    public PingResult build() {
      return new PingResult(this);
    }
  }
}
