// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../app/proto/protos.proto
package com.bubbletastic.android.ping.model.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;

public final class ProtoHost extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_HOST_NAME = "";
  public static final List<PingResult> DEFAULT_RESULTS = Collections.emptyList();

  @ProtoField(tag = 1, type = STRING)
  public final String host_name;

  @ProtoField(tag = 2, label = REPEATED, messageType = PingResult.class)
  public final List<PingResult> results;

  public ProtoHost(String host_name, List<PingResult> results) {
    this.host_name = host_name;
    this.results = immutableCopyOf(results);
  }

  private ProtoHost(Builder builder) {
    this(builder.host_name, builder.results);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ProtoHost)) return false;
    ProtoHost o = (ProtoHost) other;
    return equals(host_name, o.host_name)
        && equals(results, o.results);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = host_name != null ? host_name.hashCode() : 0;
      result = result * 37 + (results != null ? results.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ProtoHost> {

    public String host_name;
    public List<PingResult> results;

    public Builder() {
    }

    public Builder(ProtoHost message) {
      super(message);
      if (message == null) return;
      this.host_name = message.host_name;
      this.results = copyOf(message.results);
    }

    public Builder host_name(String host_name) {
      this.host_name = host_name;
      return this;
    }

    public Builder results(List<PingResult> results) {
      this.results = checkForNulls(results);
      return this;
    }

    @Override
    public ProtoHost build() {
      return new ProtoHost(this);
    }
  }
}
